# Use postgres/example user/password credentials
version: '3.1'

services:
#  db:
#    image: postgres:14-alpine
#    volumes:
#      - postgres_data_doc_bot:/var/lib/postgresql/data/
#    environment:
#      - SQL_ENGINE=django.db.backends.postgresql
#      - POSTGRES_DB=doc_bot
#      - POSTGRES_USER=cyberevil
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_HOST=db
#      - POSTGRES_PORT=5432

  # Redis
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data_doc_bot:
  media_volume:
  static_volume:
