# Generated by Django 4.1.4 on 2022-12-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_remove_goods_order"),
        ("order", "0002_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="goods",
            field=models.ManyToManyField(
                related_name="order", to="goods.goods", verbose_name="Заказы"
            ),
        ),
    ]
