# Generated by Django 4.1.4 on 2022-12-19 06:40

import django.db.models.deletion
from django.db import migrations, models

import src.goods.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                ("price", models.PositiveIntegerField(verbose_name="Цена")),
                (
                    "description",
                    models.CharField(
                        default="Пусто", max_length=150, verbose_name="Описание"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to=src.goods.models.user_directory_path,
                        verbose_name="Фото товара",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shop",
                        verbose_name="Магазин с Яндекс еды",
                    ),
                ),
            ],
        ),
    ]
