# Generated by Django 4.1.4 on 2022-12-20 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_alter_goods_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="goods",
            name="order",
        ),
    ]
