# Generated by Django 4.1.4 on 2022-12-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0006_remove_goods_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goods",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
    ]
