# Generated by Django 4.1.4 on 2022-12-19 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Логин"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Имя Фамилия"
                    ),
                ),
                (
                    "telegram_id",
                    models.BigIntegerField(
                        null=True, unique=True, verbose_name="Уникальный id в Телеграм"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата регистрации",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_authorization", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Пользователь бота",
                "verbose_name_plural": "Пользователи бота",
            },
        ),
    ]
