# Generated by Django 4.1.7 on 2023-02-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Текст сообщения, которое приходит если произошел инцидент",
                        verbose_name="Текст инцидента",
                    ),
                ),
                ("is_full", models.BooleanField(default=False)),
                (
                    "id_message",
                    models.CharField(max_length=50, verbose_name="id сообщения"),
                ),
            ],
        ),
    ]
