# Generated by Django 4.1.7 on 2023-03-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventmessage_is_sent_alter_eventmessage_id_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmessage",
            name="id_incident",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID инцидента"
            ),
        ),
        migrations.AddField(
            model_name="eventmessage",
            name="keyfields",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Ключь с ElasticSearch",
            ),
        ),
        migrations.AddField(
            model_name="eventmessage",
            name="rule_description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Описание"
            ),
        ),
        migrations.AddField(
            model_name="eventmessage",
            name="rule_info",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Наименование инцидента",
            ),
        ),
        migrations.AddField(
            model_name="eventmessage",
            name="user_info",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name=" Информация о пользователе",
            ),
        ),
    ]
