# Generated by Django 4.1.7 on 2023-04-27 13:45

from django.db import migrations, models

import src.events.models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_eventmessage_id_incident_eventmessage_keyfields_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_incident",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID инцидента",
                    ),
                ),
                (
                    "text_button",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Текст, который будет отображаться в названии кнопки",
                    ),
                ),
                (
                    "script",
                    models.FileField(
                        blank=True,
                        help_text="Запускается при нажатии на кнопку",
                        upload_to=src.events.models.user_directory_path,
                        verbose_name="Скрипт",
                    ),
                ),
            ],
        ),
    ]
